### ISSUE TITLE
Support development on MacOS (darwin-x86_64)

### ISSUE THREAD

**Issue by SanjayVas** [world-federation-of-advertisers/experimental#60]
This came up in the Tech Infra workstream as something that's desired. The goal is to be able to build and run tests on MacOS. As there are some binary dependencies that can only run on linux-x86_64, this will involve use of Docker containers in some fashion.

**Comment by oliver-amzn** [comment]
fwiw, I ran `tools/bazel-container build "//..."` and that worked.
And now I just tried:
```
➜  cross-media-measurement git:(main) ✗ tools/bazel-container build "//src/test/kotlin/org/wfanet/measurement/common/grpc:TransportSecurityTest"
Starting local Bazel server and connecting to it...
Starting local Bazel server and connecting to it...
DEBUG: /Users/ohardt/.cache/bazel/_bazel_ohardt/59bb0badc33fcb507c35661e0bc7101a/external/io_grpc_grpc_java/java_grpc_library.bzl:82:14: in srcs attribute of //imports/kotlin/io/grpc/health/v1:health_kt_jvm_grpc_DO_NOT_DEPEND_java_grpc: Proto source with label @io_grpc_grpc_proto//:health_proto should be in same package as consuming rule
DEBUG: /Users/ohardt/.cache/bazel/_bazel_ohardt/59bb0badc33fcb507c35661e0bc7101a/external/io_grpc_grpc_java/java_grpc_library.bzl:82:14: in srcs attribute of @io_grpc_grpc_java//services:_health_java_grpc: Proto source with label @io_grpc_grpc_proto//:health_proto should be in same package as consuming rule
INFO: Analyzed target //src/test/kotlin/org/wfanet/measurement/common/grpc:TransportSecurityTest (106 packages loaded, 1899 targets configured).
INFO: Found 1 target...
Target //src/test/kotlin/org/wfanet/measurement/common/grpc:TransportSecurityTest up-to-date:
  bazel-bin/src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.jar
INFO: Elapsed time: 28.039s, Critical Path: 2.46s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

fwiw, I'm putting the target in quotes to prevent zsh from expanding the `...` and same for the `...:TransportSecurityTest` target.

**Comment by SanjayVas** [comment]
Thanks. We'll close out for now and revisit if anyone else runs into issues building on MacOS via this script. We should also add docs somewhere on how to do this.

**Comment by oliver-amzn** [comment]
One thing I might want to add (in the future) is to either delete or reuse the container when building/testing, deleting it should be as simple as adding `--rm`.
The bazel directory links are all mounted on the host, right ?

**Comment by SanjayVas** [comment]
Ah, good point. Yes, all of the meaningful filesystem operations are on bind mounts. Feel free to send a PR.
